In [79]:
import pandas as pd
import numpy as np
from sklearn.multiclass import OneVsRestClassifier
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix 

In [80]:
df = pd.read_csv("/Users/maggie/Desktop/featurized/final_data_model1.csv")
df.head()

X0            X1            X2            X3            X4  \
0  5.830000e-06  1.900000e-05  7.890000e-06  6.930000e-05  3.550000e-05   
1  1.910000e-06  1.270000e-05  3.840000e-06  2.050000e-05  5.200000e-06   
2  3.180000e-08  7.810000e-07  4.440000e-08  9.000000e-07  1.400000e-07   
3  1.940000e-09  4.270000e-08  5.920000e-09  9.030000e-08  1.600000e-08   
4  1.130000e-06  6.560000e-06  9.770000e-07  7.180000e-06  2.660000e-06   

             X5            X6            X7            X8        X9  ...  \
0  1.971940e-04  2.030000e-05  2.180000e-05  1.160000e-05  0.000848  ...   
1  5.960000e-05  8.930000e-06  1.600000e-05  8.580000e-06  0.000290  ...   
2  4.270000e-06  3.080000e-07  1.320000e-06  6.610000e-07  0.000007  ...   
3  2.800000e-07  2.680000e-08  9.710000e-08  4.610000e-08  0.000002  ...   
4  2.680000e-05  2.440000e-06  1.270000e-05  6.680000e-06  0.000171  ...   

           X992          X993          X994          X995          X996  \
0  4.770000e-05  1.510000e-05  3.210000e-05  3.840000e-05  3.850000e-05   
1  3.410000e-05  6.990000e-06  1.430000e-05  1.220000e-05  3.580000e-05   
2  2.470000e-06  6.340000e-07  1.960000e-06  1.070000e-06  4.370000e-06   
3  1.600000e-07  3.090000e-08  5.370000e-08  4.210000e-08  1.080000e-07   
4  3.560000e-05  7.680000e-06  2.450000e-05  1.930000e-05  3.380000e-05   

           X997          X998      X999  \
0  8.680000e-06  2.160000e-05  0.002788   
1  4.170000e-06  1.680000e-05  0.000453   
2  2.310000e-07  1.020000e-06  0.000068   
3  1.390000e-08  1.070000e-07  0.000005   
4  5.060000e-06  7.400000e-06  0.000440   

                                               image  label  
0  media/ml_model_images/model1 /numbers-training...      7  
1  media/ml_model_images/model1 /numbers-training...      3  
2  media/ml_model_images/model1 /numbers-training...      8  
3  media/ml_model_images/model1 /numbers-training...      3  
4  media/ml_model_images/model1 /numbers-training...      5  

[5 rows x 1002 columns]

In [81]:
# split train input and output data
X = df.drop(['label',"image"], axis=1)
y = df['label']

#Print the shape of X and Y
# print(X.shape)
# print(Y.shape)

In [82]:
# Split into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


User OnevsRestClassifier in scikit learn. 

In [85]:
svm_clf = OneVsRestClassifier(SVC(kernel = 'linear', C = 1,probability = True))
svm_model = svm_clf.fit(X_train, y_train)

In [86]:
result = svm_model.predict(X_test)

In [87]:
prob = svm_model.predict_proba(X_test)
prob

array([[1.90590401e-02, 1.86551612e-03, 8.95749205e-02, 7.56671439e-02,
        7.44128393e-02, 8.48553658e-02, 6.28940286e-02, 5.71825470e-01,
        1.98456754e-02],
       [3.73847487e-01, 6.22162713e-02, 1.65219929e-01, 6.72842003e-02,
        5.98777951e-02, 5.79710196e-02, 1.23892717e-01, 1.14535541e-02,
        7.82370263e-02],
       [1.94180538e-02, 1.68541372e-03, 8.85099679e-02, 7.05981543e-02,
        5.57092720e-02, 7.71359360e-02, 6.08568125e-02, 5.97665168e-01,
        2.84212223e-02],
       [2.10759613e-02, 2.20602607e-03, 9.67582856e-02, 7.95006434e-02,
        9.29844958e-02, 8.87477478e-02, 6.48549406e-02, 5.33775198e-01,
        2.00967013e-02],
       [2.39974705e-02, 2.66613909e-03, 1.13216071e-01, 7.78305070e-02,
        1.02880244e-01, 7.86374414e-02, 7.57515858e-02, 4.78721199e-01,
        4.62993414e-02],
       [3.73847487e-01, 6.22162713e-02, 1.65219929e-01, 6.72842003e-02,
        5.98777951e-02, 5.79710196e-02, 1.23892717e-01, 1.14535541e-02,
        7.8

In [88]:
# result
# y_test

In [89]:
accuracy = svm_model.score(X_test, y_test)
accuracy

0.6

In [90]:
cm = confusion_matrix(y_test, result) 
# cm

Use Logistic Regression 

In [91]:
clf = LogisticRegression(random_state=0, multi_class='ovr')
model = clf.fit(X_train, y_train)


In [92]:
result = model.predict(X_test)
result


array([8, 7, 8, 8, 8, 7, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 7, 8, 8,
       8, 8, 8, 7, 7, 8, 1, 8, 8, 1, 1, 8, 7, 8, 8, 8, 8, 8])

In [93]:
score = model.score(X_test,y_test)
score

0.45

In [94]:
prob = model.predict_proba(X_test)
y.unique()


array([7, 3, 8, 5, 6, 0, 4, 1, 9])

In [95]:
prob

array([[0.02614773, 0.02109224, 0.13625101, 0.0923005 , 0.07778356,
        0.06189148, 0.07141188, 0.4555009 , 0.05762071],
       [0.08531882, 0.19066666, 0.04417227, 0.06582313, 0.10934258,
        0.18203936, 0.23697879, 0.04274113, 0.04291726],
       [0.0231377 , 0.01833659, 0.14000782, 0.0897288 , 0.07084171,
        0.05363228, 0.06309432, 0.48451929, 0.05670149],
       [0.02873486, 0.02412176, 0.13323746, 0.0939609 , 0.08255008,
        0.06834527, 0.07873243, 0.43182738, 0.05848986],
       [0.0288218 , 0.02592215, 0.13321041, 0.09322956, 0.08014849,
        0.06665933, 0.07951656, 0.43345794, 0.05903377],
       [0.08531882, 0.19066666, 0.04417227, 0.06582313, 0.10934258,
        0.18203936, 0.23697879, 0.04274113, 0.04291726],
       [0.03606592, 0.03610043, 0.12507528, 0.09657583, 0.09156654,
        0.08390077, 0.10017503, 0.36961322, 0.06092698],
       [0.05127089, 0.07099961, 0.10582064, 0.09655789, 0.10421901,
        0.11426079, 0.14605843, 0.24843661, 0.06237613],
